name: Upload binaries to S3

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Make binaries
        uses: sosedoff/actions/golang-build@master
        with:
          args: linux/amd64 darwin/amd64
        env:
          COMPRESS_FILES: 1

      - name: Upload to Amazon S3
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 cp --acl public-read --recursive --exclude '*' --include '*' /github/workspace/.release/ s3://pgweb-github-builds/${{ github.ref }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        